# Form implementation generated from reading ui file 'dat_ve.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon

from home_nv.chuc_nang_nv.trang_chu import ChucNang
from home_nv.chuc_nang_nv.dat_ve import ChucNangDV
from home_nv.them_khach import Ui_TKWindow


class Ui_DVWindow(object):
    def __init__(self,gia_tri=None):
        self.gia_tri = gia_tri
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 404)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 221, 41))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.txt_id = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_id.setGeometry(QtCore.QRect(70, 100, 181, 31))
        self.txt_id.setObjectName("txt_id")
        self.txt_gia = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_gia.setGeometry(QtCore.QRect(70, 190, 181, 31))
        self.txt_gia.setObjectName("txt_gia")
        self.txt_sdt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_sdt.setGeometry(QtCore.QRect(370, 190, 181, 31))
        self.txt_sdt.setObjectName("txt_sdt")
        self.txt_sdt.setFocus()
        self.txt_ten = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_ten.setGeometry(QtCore.QRect(370, 100, 181, 31))
        self.txt_ten.setObjectName("txt_ten")
        self.btn_dat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_dat.setGeometry(QtCore.QRect(350, 290, 101, 41))
        self.btn_dat.setStyleSheet("background-color : rgb(19, 255, 3);\n"
"font-weight : bold;\n"
"color : white")
        self.btn_dat.setObjectName("btn_dat")
        self.btn_huy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_huy.setGeometry(QtCore.QRect(190, 290, 101, 41))
        self.btn_huy.setStyleSheet("background-color : rgb(255, 55, 15);\n"
"font-weight : bold;\n"
"color : white")
        self.btn_huy.setObjectName("btn_huy")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 110, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 200, 47, 13))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 627, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.nhan_du_lieu()
        self.btn_dat.clicked.connect(self.dat)
        self.btn_dat.setIcon(QIcon("../image/add.png"))
        self.btn_dat.setIconSize(QSize(25,25))
        self.btn_huy.setIcon(QIcon("../image/delete.png"))
        self.btn_huy.setIconSize(QSize(25,25))
        self.btn_huy.clicked.connect(self.huy)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ĐẶT VÉ TÀU HỎA"))
        self.btn_dat.setText(_translate("MainWindow", "Đặt vé"))
        self.btn_huy.setText(_translate("MainWindow", "Hủy"))
        self.label_2.setText(_translate("MainWindow", "ID VÉ"))
        self.label_3.setText(_translate("MainWindow", "GIÁ TIỀN"))
        self.label_4.setText(_translate("MainWindow", "TÊN TÀU"))
        self.label_5.setText(_translate("MainWindow", "SĐT"))
    def nhan_du_lieu(self):
        if len(self.gia_tri) > 2:
            self.txt_id.setPlainText(self.gia_tri[0])
            self.txt_gia.setPlainText(self.gia_tri[1])
            self.txt_ten.setPlainText(self.gia_tri[3])
    def dat(self):
        cn = ChucNangDV()
        sdt = self.txt_sdt.toPlainText()
        id_khach = cn.lay_khach_theo_sdt(sdt)
        if id_khach != 0 :
            id_ve = self.txt_id.toPlainText()
            cn.dang_ki_ve(id_ve,id_khach)
            self.MainWindow.close()
        else:
            self.mo_them_khach(sdt)

    def mo_them_khach(self,sdt=""):
        self.window = QtWidgets.QMainWindow()
        self.them = Ui_TKWindow(sdt)
        self.them.setupUi(self.window)
        self.window.show()
    def huy(self):
        self.MainWindow.close()