# Form implementation generated from reading ui file 'them_khach.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QSize
from PyQt6.QtGui import QIcon
from PyQt6.QtWidgets import QMessageBox

from home_nv.chuc_nang_nv.them_khach import ChucNangTK

class Ui_TKWindow(object):
    def __init__(self,sdt = ""):
        self.sdt = sdt
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(426, 326)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 131, 21))
        self.label.setStyleSheet("font-weight : bold")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 60, 231, 16))
        self.label_2.setStyleSheet("color : red")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 100, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 170, 51, 21))
        self.label_4.setObjectName("label_4")
        self.txt_ten = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_ten.setGeometry(QtCore.QRect(160, 100, 151, 31))
        self.txt_ten.setObjectName("txt_ten")
        self.txt_sdt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_sdt.setGeometry(QtCore.QRect(160, 160, 151, 31))
        self.txt_sdt.setObjectName("txt_sdt")
        self.btn_them = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_them.setGeometry(QtCore.QRect(240, 230, 111, 41))
        self.btn_them.setStyleSheet("background-color :rgb(72, 255, 16);\n"
"color : white;\n"
"font-weight : bold")
        self.btn_them.setObjectName("btn_them")
        self.btn_huy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_huy.setGeometry(QtCore.QRect(80, 230, 111, 41))
        self.btn_huy.setStyleSheet("background-color :rgb(255, 15, 7);\n"
"color : white;\n"
"font-weight : bold")
        self.btn_huy.setObjectName("btn_huy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 426, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.nap_du_lieu()
        self.btn_huy.clicked.connect(self.huy)
        self.btn_them.clicked.connect(self.them)
        self.btn_them.setIcon(QIcon("../image/add.png"))
        self.btn_them.setIconSize(QSize(25,25))
        self.btn_huy.setIcon(QIcon("../image/delete.png"))
        self.btn_huy.setIconSize(QSize(25,25))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Thêm mới khách hàng"))
        self.label_2.setText(_translate("MainWindow", "khách hàng không tồn tại hãy thêm mới"))
        self.label_3.setText(_translate("MainWindow", "Tên"))
        self.label_4.setText(_translate("MainWindow", "Sdt"))
        self.btn_them.setText(_translate("MainWindow", "Thêm"))
        self.btn_huy.setText(_translate("MainWindow", "Hủy"))
    def nap_du_lieu(self):
        self.txt_sdt.setPlainText(self.sdt)
    def huy(self):
        self.MainWindow.close()
    def them(self):
        ten = self.txt_ten.toPlainText()
        sdt = self.txt_sdt.toPlainText()
        tk = ChucNangTK()
        tk.them_khach(ten, sdt)
        mess = QMessageBox()
        mess.setWindowTitle("thông báo")
        mess.setText("đăng kí thành công")
        mess.setIcon(QMessageBox.Icon.Information)
        mess.setStandardButtons(QMessageBox.StandardButton.Ok)
        mess.exec()
        self.MainWindow.close()
